You are given three tables 
a) Account which contains Account id 
b) Date That contains dateid 
c) Sales Fact with three columns date, Account Id and revenue . 
This fact records the revenue generated by an account every day if they spend. 
If there is no spend then there won't be a record in the fact table . 
Given this scenario write an SOL that generates a list of all Accounts on every day in the last one Month that had no spent.
The Question #1 above requires a cross join with Accounts and Dates and lead to a large table if your account dimension is big. 
How could you optimize this from a design perspective? => Answer could be datelist, bitmap integer etc.

SELECT temp.date_id, temp.account_id
from
(SELECT a.account_id, d.date
from account a
CROSS JOIN date d
WHERE d.date > CURRENT_DATE - INTERVAL '29' DAY) temp
left outer join sales s
ON temp.account_id = s.account_id
AND temp.date = s.date
WHERE s.date IS NULL
AND s.account_id IS NULL
